from __future__ import annotations

import asyncio
import json
import uuid
from dataclasses import dataclass
from typing import AsyncGenerator

from openai import AsyncOpenAI
from rixs_app.agent.auth import CBORG_BASE_URL, CBORG_DEFAULT_MODEL
from rixs_app.agent.tools import ToolRegistry
from rixs_app.agent.system_prompt import build_system_prompt


@dataclass
class AgentEvent:
    """Represents an event generated by the agent engine."""
    type: str  # 'token', 'tool_start', 'tool_output', 'approval_required', 'status', 'error', 'done'
    content: str = ''
    metadata: dict | None = None


class CborgAgentEngine:
    """Agent engine handling LLM communication and tool dispatch."""
    
    def __init__(self, api_key: str, base_url: str = CBORG_BASE_URL, model: str = CBORG_DEFAULT_MODEL, registry: ToolRegistry = None):
        """Initializes the Agent Engine.
        
        Args:
            api_key (str): The CBORG API Key.
            base_url (str): The CBORG base URL.
            model (str): The model string to use.
            registry (ToolRegistry): The initialized ToolRegistry.
        """
        self.client = AsyncOpenAI(api_key=api_key, base_url=base_url)
        self.model = model
        self.registry = registry
        
        self._terminal_access = False
        self.conversation_history = [{"role": "system", "content": build_system_prompt(self._terminal_access)}]
        
        self._pending_approvals: dict[str, asyncio.Event] = {}
        self._pending_results: dict[str, str] = {}
        self._cancel_flag = False
        self._loop: asyncio.AbstractEventLoop | None = None  # set by bridge before use

    def set_model(self, model_id: str) -> None:
        """Updates the language model."""
        self.model = model_id

    def set_terminal_access(self, enabled: bool) -> None:
        """Updates terminal access flag and rebuilds the system prompt."""
        self._terminal_access = enabled
        self.conversation_history[0]["content"] = build_system_prompt(self._terminal_access)

    def reset(self) -> None:
        """Clears conversation history."""
        self.conversation_history = [{"role": "system", "content": build_system_prompt(self._terminal_access)}]
        self._cancel_flag = False

    def cancel(self) -> None:
        """Cancels any active generation."""
        self._cancel_flag = True
        for event in self._pending_approvals.values():
            if self._loop:
                self._loop.call_soon_threadsafe(event.set)
            else:
                event.set()

    def approve_tool(self, callback_id: str) -> None:
        """Approves a pending tool execution (thread-safe)."""
        if callback_id in self._pending_approvals:
            self._pending_results[callback_id] = "APPROVED"
            evt = self._pending_approvals[callback_id]
            if self._loop:
                self._loop.call_soon_threadsafe(evt.set)
            else:
                evt.set()

    def reject_tool(self, callback_id: str, feedback: str) -> None:
        """Rejects a pending tool execution with feedback (thread-safe)."""
        if callback_id in self._pending_approvals:
            self._pending_results[callback_id] = f"REJECTED: {feedback}"
            evt = self._pending_approvals[callback_id]
            if self._loop:
                self._loop.call_soon_threadsafe(evt.set)
            else:
                evt.set()

    async def stream_chat(self, user_message: str, gui_context: str) -> AsyncGenerator[AgentEvent, None]:
        """Streams chat completion responses and handles multi-step tool calls.
        
        Args:
            user_message (str): The user's prompt.
            gui_context (str): Serialized GUI context to append to the prompt.
            
        Yields:
            AgentEvent: Events for tokens, tool calls, and completion.
        """
        tagged_message = f"{user_message}\n\n[GUI Context: {gui_context}]"
        self.conversation_history.append({"role": "user", "content": tagged_message})
        
        rounds = 0
        while rounds < 8:
            if self._cancel_flag:
                break
            rounds += 1
            
            kwargs = {
                "model": self.model,
                "messages": self.conversation_history,
                "stream": True,
            }
            if self.registry and self.registry.get_tool_schemas():
                kwargs["tools"] = self.registry.get_tool_schemas()
                
            stream = await self.client.chat.completions.create(**kwargs)
            
            tool_calls_data = {}
            
            async for chunk in stream:
                if self._cancel_flag:
                    break
                if not chunk.choices:
                    continue
                    
                delta = chunk.choices[0].delta
                if delta.content:
                    yield AgentEvent(type='token', content=delta.content)
                    
                if delta.tool_calls:
                    for tc in delta.tool_calls:
                        idx = tc.index
                        if idx not in tool_calls_data:
                            tool_calls_data[idx] = {'id': '', 'name': '', 'arguments': ''}
                        if tc.id:
                            tool_calls_data[idx]['id'] = tc.id
                        if tc.function and tc.function.name:
                            tool_calls_data[idx]['name'] = tc.function.name
                        if tc.function and tc.function.arguments:
                            tool_calls_data[idx]['arguments'] += tc.function.arguments
                            
            if not tool_calls_data:
                yield AgentEvent(type='done')
                break
                
            # Process tool calls
            tool_calls_formatted = []
            for idx, tc in tool_calls_data.items():
                tool_calls_formatted.append({
                    "id": tc['id'],
                    "type": "function",
                    "function": {
                        "name": tc['name'],
                        "arguments": tc['arguments']
                    }
                })
            
            self.conversation_history.append({
                "role": "assistant",
                "content": None,
                "tool_calls": tool_calls_formatted
            })
            
            for tc in tool_calls_data.values():
                tool_name = tc['name']
                args_str = tc['arguments']
                tool_id = tc['id'] or uuid.uuid4().hex[:8]
                
                try:
                    kwargs_dict = json.loads(args_str)
                except json.JSONDecodeError:
                    kwargs_dict = {}
                
                if self.registry.requires_approval(tool_name):
                    callback_id = uuid.uuid4().hex[:8]
                    event = asyncio.Event()
                    self._pending_approvals[callback_id] = event
                    
                    yield AgentEvent(type='approval_required', content=tool_name, metadata={'callback_id': callback_id, 'call_id': tool_id, 'args': args_str})
                    await event.wait()
                    
                    result_feedback = self._pending_results.get(callback_id, "REJECTED: Unknown")
                    
                    if result_feedback == "APPROVED":
                        yield AgentEvent(type='tool_start', content=tool_name, metadata={'call_id': tool_id, 'args': args_str})
                        result = await self.registry.execute(tool_name, kwargs_dict)
                        yield AgentEvent(type='tool_output', content=tool_name, metadata={'call_id': tool_id, 'output': result})
                    else:
                        result = result_feedback
                    
                    if callback_id in self._pending_approvals:
                        del self._pending_approvals[callback_id]
                        
                else:
                    yield AgentEvent(type='tool_start', content=tool_name, metadata={'call_id': tool_id, 'args': args_str})
                    result = await self.registry.execute(tool_name, kwargs_dict)
                    yield AgentEvent(type='tool_output', content=tool_name, metadata={'call_id': tool_id, 'output': result})
                    
                self.conversation_history.append({
                    "role": "tool",
                    "tool_call_id": tool_id,
                    "name": tool_name,
                    "content": result
                })
