"""Parser for RIXS zeroth-order scan log TXT files.

These files are generated by the RIXS beamline control software and contain
tab-separated scan data rows with one row per acquired frame. The 46-column
format includes motor positions and the filename of the corresponding Marana
CCD image.

File format:
- Lines 1–14: Header metadata (date, motor name, start/stop/increment, description)
- Line 15: Tab-separated column headers (46 columns total)
- Lines 16+: Tab-separated data rows

Key columns (0-indexed):
- Column 2: "<MotorName> Goal" — commanded motor position for this row
- Column 3: "<MotorName> Actual" — actual achieved motor position
- Column 45: "Marana" — Windows-style relative path to the acquired image
"""

import os


HEADER_LINES = 14  # Lines before the column header row
_MOTOR_NAME_LINE = 3  # 0-indexed — "SM3 Mirror Pitch"
_COL_MARANA = 45  # 0-indexed column for the Marana file path


def parse_scan_log(txt_path: str) -> dict:
    """Parse a RIXS single motor scan log TXT file.

    Args:
        txt_path: Absolute or relative path to the .txt scan log file.

    Returns:
        A dict with the following structure::

            {
                'motor_name': str,          # e.g. "SM3 Mirror Pitch"
                'start': float,
                'stop': float,
                'increment': float,
                'frames': {
                    '<basename>.tiff': {
                        'motor_goal': float,
                        'motor_actual': float,
                        'row_index': int,
                    },
                    ...
                }
            }

    Raises:
        FileNotFoundError: If txt_path does not exist.
        ValueError: If the file format is not recognised (fewer than HEADER_LINES+1 lines,
                    wrong number of columns, etc.).
    """
    if not os.path.exists(txt_path):
        raise FileNotFoundError(f"Scan log not found: {txt_path}")

    with open(txt_path, "r", encoding="utf-8", errors="replace") as f:
        raw_lines = f.readlines()

    # Strip carriage returns (Windows CRLF)
    lines = [l.rstrip("\r\n") for l in raw_lines]

    if len(lines) < HEADER_LINES + 2:
        raise ValueError(
            f"Scan log has only {len(lines)} lines; expected at least {HEADER_LINES + 2}."
        )

    # Extract motor name from header line 4 (0-indexed line 3)
    motor_name = lines[_MOTOR_NAME_LINE].strip()

    # Extract start / stop / increment
    start = stop = increment = None
    for line in lines[:HEADER_LINES]:
        if line.startswith("Start:"):
            try:
                start = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("Stop:"):
            try:
                stop = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif line.startswith("Increment:"):
            try:
                increment = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass

    # Line HEADER_LINES (0-indexed) is the column header row
    col_header_line = lines[HEADER_LINES]
    col_headers = col_header_line.split("\t")

    # Identify the "Goal" and "Actual" column indices dynamically
    goal_col = None
    actual_col = None
    marana_col = None
    for i, h in enumerate(col_headers):
        if h.strip().lower().endswith("goal"):
            goal_col = i
        if h.strip().lower().endswith("actual"):
            actual_col = i
        if h.strip().lower() == "marana":
            marana_col = i

    if marana_col is None:
        # Fallback to fixed column 45
        marana_col = _COL_MARANA
    if goal_col is None:
        goal_col = 2
    if actual_col is None:
        actual_col = 3

    frames = {}
    for row_idx, line in enumerate(lines[HEADER_LINES + 1:]):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < max(goal_col, actual_col, marana_col) + 1:
            continue  # Malformed row — skip silently

        try:
            motor_goal = float(parts[goal_col])
        except ValueError:
            motor_goal = float("nan")

        try:
            motor_actual = float(parts[actual_col])
        except ValueError:
            motor_actual = float("nan")

        raw_path = parts[marana_col].strip()
        # Convert Windows-style backslash path to just the basename
        # e.g. "..\Single Motor Scan 004202 Images\Single Motor Scan 004202 Marana 000.tiff"
        basename = os.path.basename(raw_path.replace("\\", os.sep))
        if not basename:
            continue

        frames[basename] = {
            "motor_goal": motor_goal,
            "motor_actual": motor_actual,
            "row_index": row_idx,
        }

    return {
        "motor_name": motor_name,
        "start": start,
        "stop": stop,
        "increment": increment,
        "frames": frames,
    }


def validate_tif_coverage(file_list: list, metadata: dict) -> tuple[list, list]:
    """Cross-check a list of TIF files against parsed scan log metadata.

    Args:
        file_list: List of absolute TIF file paths from the GUI file list.
        metadata: Parsed metadata dict from parse_scan_log().

    Returns:
        A 2-tuple of (matched_paths, unmatched_paths) where:
        - matched_paths: TIF paths whose basenames are found in the scan log.
        - unmatched_paths: TIF paths whose basenames are NOT in the scan log.
    """
    known = set(metadata.get("frames", {}).keys())
    matched = []
    unmatched = []
    for path in file_list:
        bn = os.path.basename(path)
        if bn in known:
            matched.append(path)
        else:
            unmatched.append(path)
    return matched, unmatched
